### ISSUE TITLE
The import column of the custom item

### ISSUE THREAD

**Issue by stevetBaBy** [codingchili/ethereum-ingest#22]
Hello, developer, and I think there is only part of the data imported into the database, such as the block data GasLimit, which I did not see when I used MogoDB.I think you can add configuration files and customize them

**Comment by codingchili** [comment]
Hello,

StorableBlock & StorableTransaction contains the fields that are indexed

https://github.com/codingchili/ethereum-ingest/tree/master/src/main/java/com/codingchili/ethereumingest/model

I haven't used this tool in a while so maybe some of the data is indeed missing.
